version: 0.2
phases:
    pre_build:
        commands:
            - echo "AWS_REGION is $AWS_REGION "
            - REPOSITORY_URI_RADDB="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/govwifi/$STAGE/raddb"
            - echo "REPOSITORY_URI_RADDB is $REPOSITORY_URI_RADDB"

            - REPOSITORY_URI_RADDB_IRE="$AWS_ACCOUNT_ID.dkr.ecr.eu-west-1.amazonaws.com/govwifi/$STAGE/raddb"
            - echo "REPOSITORY_URI_RADDB_IRE is $REPOSITORY_URI_RADDB_IRE"

            - REPOSITORY_URI_FE="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/govwifi/$STAGE/frontend"
            - echo "REPOSITORY_URI_FE is $REPOSITORY_URI_FE"

            - REPOSITORY_URI_FE_IRE="$AWS_ACCOUNT_ID.dkr.ecr.eu-west-1.amazonaws.com/govwifi/$STAGE/frontend"
            - echo "REPOSITORY_URI_FE_IRE is $REPOSITORY_URI_FE_IRE"

            - echo "$DOCKER_HUB_AUTHTOKEN_ENV" | docker login -u $(echo $DOCKER_HUB_USERNAME_ENV) --password-stdin
            - IMAGE_TAG="latest"

            - echo "Acceptance tests project name is $ACCEPTANCE_TESTS_PROJECT_NAME"
            - BUILD_ID=$(aws codebuild start-build --project-name $ACCEPTANCE_TESTS_PROJECT_NAME | jq -r '.build.id')
            - echo "Acceptance tests have started. BUILD_ID is $BUILD_ID"
            - BUILD_STATUS=$(aws codebuild batch-get-builds --ids $BUILD_ID | jq -r '.builds[].buildStatus')
            - echo "Build status is $BUILD_STATUS"
            - |
              while [ $BUILD_STATUS = "IN_PROGRESS" ] ; do
                  echo "Build status is $BUILD_STATUS"
                  BUILD_STATUS=$(aws codebuild batch-get-builds --ids $BUILD_ID | jq -r '.builds[].buildStatus')
                  if [ $BUILD_STATUS = "FAILED" ]
                  then
                    echo "Frontend acceptance tests have failed. Please inspect them $BUILD_ID"
                    exit 1;
                    break
                  elif [ $BUILD_STATUS = "SUCCEEDED" ]
                  then
                    echo "Acceptance tests successful."
                    break
                  fi
                  echo "Acceptance tests status is $BUILD_STATUS"
                  sleep 30s
                done

    build:
        commands:
            - echo Build started on `date`
            - echo "Building raddb Docker images..."

            - docker build -t $REPOSITORY_URI_RADDB:$IMAGE_TAG -f Dockerfile.raddb .
            - echo "Building frontend Docker image..."
            - docker build -t $REPOSITORY_URI_FE:$IMAGE_TAG -f Dockerfile .

            - docker build -t $REPOSITORY_URI_RADDB_IRE:$IMAGE_TAG -f Dockerfile.raddb .
            - echo "Building frontend Docker image..."
            - docker build -t $REPOSITORY_URI_FE_IRE:$IMAGE_TAG -f Dockerfile .
    post_build:
        commands:
            - echo "Pushing the Docker images..."
            - echo "Logging into AWS ECR eu-west-2"
            - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

            - echo "Pushing raddb image eu-west-2"
            - docker push $REPOSITORY_URI_RADDB:$IMAGE_TAG

            - echo "Pushing frontend image eu-west-2"
            - docker push $REPOSITORY_URI_FE:$IMAGE_TAG

            - echo "Logging into AWS ECR eu-west-1"
            - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.eu-west-1.amazonaws.com

            - echo "Pushing raddb image to eu-west-1"
            - docker push $REPOSITORY_URI_RADDB_IRE:$IMAGE_TAG

            - echo "Pushing frontend image to eu-west-1"
            - docker push $REPOSITORY_URI_FE_IRE:$IMAGE_TAG
