#!/usr/bin/perl

use strict;
use warnings;

use Data::Dumper;
use Digest::MD5 qw(md5_hex);
use Fcntl qw(:DEFAULT :flock);
use FindBin ();
use Getopt::Long ();
use JSON ();
use Math::BigInt ();

# Important things to note regarding this script:
#   1. Gets an exclusive lock on pid file (LOCK_EX) nonblocking - and exits on failure,
#      this ensures only one script can run at a time, the lock is released on program
#      completion. (flocks in unix are released when process exits - unlike windows)
#   2. It checks for rotated file - and if present logs error and reprocesses it
#   3. If no rotated file, rotates the file, sleeps for period to allow the govlogger
#      module to close all descriptors
#   4. Reads in the previous unprocessed log items, and then starts processing the log lines
#   5. At end of file, writes out unprocessed log items and deletes rotated logfile.
#
# The expiry of uncomplete log lines is important. The time to expire is taken from the time
# of the log line being processed, not the time now - this helps if we have a logging backlog, as now may
# be far ahead of the current line being processed. This is subtle.

# Fields shared between requests
my @COMMON_FIELDS   = qw(Connect-Info Framed-MTU Calling-Station-Id User-Name NAS-Port-Type NAS-IP-Address eap_sessions);

# Fields used to create a UUID for the request
my @UUID_FIELDS     = qw(User-Name NAS-IP-Address Calling-Station-Id);

# Fields used to deduplicate packets between requests
my @FIELDS_TO_DEDUP = qw(Stage EAP-Type TLS-Session-Cipher-Suite);

# Parse the many command line options...
my (
    $pretty, $help, $canonical, $statefile, $flush,
    $logfile, $wait, $last_date_only, $drop_eap_peap,
    $expiry_seconds, $unittests, $reduce_duplicates);

Getopt::Long::GetOptions(
    canonical             => \$canonical,
    'expires=i'           => \$expiry_seconds,
    flush                 => \$flush,
    help                  => \$help,
    'logfile=s'           => \$logfile,
    pretty                => \$pretty,
    reduce_duplicates     => \$reduce_duplicates,
    reduce_last_date_only => \$last_date_only,
    reduce_drop_eap_peap  => \$drop_eap_peap,
    'state=s'             => \$statefile,
    unittests             => \$unittests,
    'wait=i'              => \$wait,
)
    or die("Invalid command line options:\n" . usage());

# Display help and exit if requested
if ($help) {
    print usage();
    exit;
}

$expiry_seconds ||= 30;

# Nasty having unit tests in program - but it was quick
if ($unittests) {
    unittests();
    exit;
}

# Ensure we are not already running by getting an exlusive filelock on a pid file
my $pid_filename = '/var/run/lock/process_gov_logs.pid';
my $pid_filehandle = create_pid_file($pid_filename);

#
# Create JSON output formatter and parser
#
$pretty ||= 0;
$canonical ||= 0;
my $json = JSON->new;
$json->pretty($pretty);
$json->canonical($canonical);

# We keep loglines by Uuid and in a linked list (doubly)
# We should probably have an object here as it's messy
my $lines_by_uuid = {};
my $items_by_utime_start;
my $items_by_utime_end;

#
# Handle previous state, and saving state at the end
#
my $state_handle;
if ($statefile) {
    #
    # First try to restore previous state
    #
    $state_handle = IO::File->new($statefile, 'r');

    if ($state_handle) {
        restore_linked_items($state_handle);
        $state_handle->close;
    }

    # If we are flushing all output - we will not leave any state remaining...
    if ($flush) {
        undef $state_handle;
        unlink $statefile;
    }
    else {
        $state_handle = IO::File->new($statefile, 'w')
            or die("Cannot open $statefile for write: $!\n");
        print STDERR "Opened $statefile write for remaining event on exit\n";
    }
}

#
# By default read from STDIN, but if file specified, see if rotated file,
# if rotated file process that, and exit, else rotate...
#
my $ih = *STDIN;
my $rotated_file;
if ($logfile) {
    # We cannot rotate if the wait time has not been specified
    die("Cannot rotate logfile as no wait specified\n" . usage()) if !$wait;

    $rotated_file = "$logfile.rotated";

    # Is there a rotated logfile???
    $ih = IO::File->new($rotated_file, 'r');
    if ($ih) {
        print STDERR "Previous rotated file $rotated_file failed to be processed.... trying again\n";
    }
    else {
        # No existing rotated logfile - rotate, wait then process...
        # there is no race condition here as we have a lock and nobody
        # else whould be rotating the logfile
        if (!rename($logfile, $rotated_file)) {
            die("Failed to rename $logfile to $rotated_file: $!\n");
        }
        print STDERR "Renamed $logfile $rotated_file\n";
        
        # Now sleep until freeradius has finished writing....
        print STDERR "Sleeping for $wait seconds before processing $rotated_file\n";
        sleep $wait;

        # Finally open file read
        $ih = IO::File->new($rotated_file, 'r');
        if (!$ih) {
            die("Failed to open rotated logfile $rotated_file for read: $!\n");
        }
    }
}

#
# Now read all items from input stream....
#
while (my $line = $ih->getline) {

    my $data = parse_line($line);
    next if !$data;

    # We are not interested in proxied data - as EAP-PEAP
    next if $data->{'FreeRADIUS-Proxied-To'};

    # We use the Uuid to identify packets from same client, this might not be right,
    # but best we can do
    my $Uuid  = $data->{Uuid};
    my $unixtime = delete $data->{Unixtime};

    my $entry = delete $lines_by_uuid->{$Uuid};

    # If we have a previous line by this Uuid add data to it
    if ($entry) {
        remove_item_from_linked_list($entry);
        $entry->{Unixtime} = $unixtime;
        push @{ $entry->{lines} }, $data;
    }

    #
    # Otherwise create a new log entry
    #
    else {
        $entry = {
            Unixtime     => $unixtime,
            Uuid         => $Uuid,
            lines        => [],
        };

        #
        # If an identity packet - lets mark this as start and log nothing
        # We just set the StartDate for the events
        #
        if (($data->{'EAP-Type'} eq 'Identity') && ($data->{Stage} eq 'authorize')) {
            $entry->{StartDate} = $data->{Date};
        }
        else {
            push @{ $entry->{lines} }, $data;
        }
    }

    #
    # If its a post-auth packet lets output and move on....
    if ($data->{Stage} eq 'post-auth') {
        send_to_log($entry);
        next;
    }

    # OK - Add back into the hash and linked list
    $lines_by_uuid->{$Uuid} = $entry;
    add_item_to_list($entry);

    # As we have a log event we have the Unixtime, we can use this to expire older items in the
    # linked list
    my $expiry_date = $entry->{Unixtime} - $expiry_seconds;

    # Delete items in linked list that have expired, these will be at the start
    my $item = $items_by_utime_start;
    while ($item && ($item->{Unixtime} < $expiry_date)) {
        # Remove item from linked list
        remove_item_from_linked_list($item);
    
        # Remove from Uuid map
        delete $lines_by_uuid->{$item->{Uuid}};

        # Log and look at next item
        send_to_log($item);
        $item = $item->{next};
    }
}

#
# If we have a state file to store items remaining
# output the data to this file and exit
#
if ($state_handle) {
    save_linked_items($state_handle);
}
else {
    # Otherwise output the remaining items
    while ($items_by_utime_start) {
        send_to_log($items_by_utime_start);
        $items_by_utime_start = $items_by_utime_start->{next};
    }
}

# Have we got a rotated file - we've processed it - so delete
unlink $rotated_file if $rotated_file;

# Finally we should delete the pidfile (for cleanliness)
# Note we delete first, which does allow somebody to start running here, but as we are all done
# it no longer matters....
unlink $pid_filename;
exit;


sub send_to_log {
    my ($item) = @_;

    # Get shared data
    my $lines = $item->{lines};

    my $last_line = $lines->[$#$lines];

    # If option reduce_drop_eap_peap we skip PEAP messages
    return if $drop_eap_peap && $last_line->{'EAP-Type'} eq 'PEAP';

    my $shared = { StartDate => $item->{StartDate }};
    foreach my $field (@COMMON_FIELDS) {
        $shared->{$field} = $last_line->{$field};
    }

    my $previous_line;
    LINE: foreach my $line (@$lines) {
        delete @$line{(@COMMON_FIELDS, 'Expires', 'Uuid')};
        # If TLS Session info same as previous - dont log...

        # If we have lines with repeating patterns - we can sqaush them together
        if ($reduce_duplicates && $previous_line) {
            my $dedup_count = 0;
            foreach my $dedup_field (@FIELDS_TO_DEDUP) {

                my $last_value = $previous_line->{$dedup_field};
                my $current_value = $line->{$dedup_field};
                $current_value = $json->encode($current_value) if ref($current_value);

                if ($last_value && $current_value) {
                    if ($last_value eq $current_value) {
                        $dedup_count++;
                    }
                }
            }

            # Get the key count for the previous and this line
            my $key_count = scalar keys %$line;
            my $previous_key_count = scalar keys %$previous_line;

            if (($dedup_count == $key_count - 1) && ($key_count == $previous_key_count)) {
                #
                # Squash identical lines to array of dates, or just the last date
                # if reduce_last_date_only option set
                #
                if ($last_date_only) {
                    $previous_line->{Date} = $line->{Date};
                }
                else {
                    my $date = $previous_line->{Date};
                    if (ref($date)) {
                        push @$date, $line->{Date};
                    }
                    else {
                        $previous_line->{Date} = [ $previous_line->{Date}, $line->{Date} ];
                    }
                }
                next LINE;
            }
        }
        $previous_line = $line;
        push @{ $shared->{lines} }, $line;
    }
    print  $json->encode($shared),"\n";
}

sub add_item_to_list {
    my ($item) = @_;

    delete $item->{prev};
    delete $item->{next};
    if (!$items_by_utime_end) {
        $items_by_utime_end = $items_by_utime_start = $item;
        return;
    }

    # It is most likely the expiry time will be greater than the end of the list
    # so we will start looking at the end

    my $utime = $item->{Unixtime};

    # After is the item we want to insert after....
    my $after = $items_by_utime_end;
    my $is_end = 1;
    while ($after->{Unixtime} > $utime) {
        $is_end = 0;
        my $previous = $after->{prev};
        
        # If we havnt a previous we want to insert at the start
        if (!$previous) {
            $items_by_utime_start->{prev} = $item;
            $item->{next} = $items_by_utime_start;
            $items_by_utime_start = $item;
            return;
        }
            
        $after = $previous;
    }

    if ($is_end) {
        $items_by_utime_end->{next} = $item;
        $item->{prev} = $items_by_utime_end;
        $items_by_utime_end = $item;
        return;
    }

    # At this point their must be a next - as is_end is false
    my $next = $after->{next};

    $after->{next} = $item;
    $item->{prev} = $after;
    $item->{next} = $next;

    $next->{prev} = $item;
}
        

sub remove_item_from_linked_list {
    my ($item) = @_;

    my $prev = $item->{prev};
    my $next = $item->{next};
    if ($prev) {
        $prev->{next} = $next;
    }
    else {
        $items_by_utime_start = $next;
    }

    if ($next) {
        $next->{prev} = $prev;
    }
    else {
        $items_by_utime_end = $prev;
    }
    delete $item->{prev};
    delete $item->{next};
    return $item;
}

sub parse_line {
    my ($line) = @_;

    #
    # The open close statements are not worth trying to parse
    # they are generated when govlogger closes the file
    #
    return if $line =~ m/^GovLogger closing/;

    if ($line =~ m/^(\d+\.\d+)\s+(.*?): (.+)/) {
        my ($date, $stage, $j) = ($1,$2, $3);

        my $data;
        {
            local $@;
            eval {
                $data = $json->decode($j);
            };
            if ($@) {
                print STDERR "Got JSON error decoding:\n$j$_\n\n";
            }
        }
        return if !$data;

        # Put session and request vars into same map, and add the Stage
        my $flattened = {%{ $data->{Request} }, %{ $data->{Session} }, Stage => $stage };

        # Turn the date into 64 bit integer, unixtime * 1,000,000 with microseconds added
        if ($date =~ /^(\d+)\.(\d+)$/) {
            $flattened->{Date} = (Math::BigInt->new($1) * 1000000 + Math::BigInt->new($2))->bstr;

            # We will use the Unixtime seconds to work out if the log event has expired..
            $flattened->{Unixtime} = $1;
        }
        else {
            $flattened->{Date} = $date;
            #
            # We failed to get date as seconds.microseconds so lets use now for Unixtime - this is ugly
            #
            $flattened->{Unixtime} = time;
        }
        $flattened->{Uuid} = md5_hex( join('|', @$flattened{@UUID_FIELDS}) );
        return $flattened;
    }
    else {
        print STDERR "ERROR line syntax wrong: $line";
        return undef;
    }
}

sub restore_linked_items {
    my ($file) = @_;

    my $text = '';
    while (my $line = $file->getline) {
        $text .= $line;
    }

    my $items;
    {
        local $@;
        eval {
            $items = $json->decode($text);
        };
        die("Failed to decode JSON from state file: $@\n")
            if $@;
    }

    foreach my $item (@$items) {
        add_item_to_list($item);
        $lines_by_uuid->{ $item->{Uuid} } = $item;
    }
}

sub save_linked_items {
    my ($file) = @_;

    my @to_write;
    my $item = $items_by_utime_start;

    while ($item) {
        my $next = delete $item->{next};    
        delete $item->{prev};

        push @to_write, $item;
        $item = $next;
    }

    $file->print($json->encode(\@to_write));
}

        

sub usage {
    return $FindBin::Script . ' [--help|-h] [--pretty|-p] [--canonical|-c] [--state statefile]
    [--wait|-w seconds] [--logfile|-l logfile] [--expires|-e seconds]
Read from log data from freeradius using the govlogger and output structured JSON log events.
Data is read until end of stream or file. The program uses a pidfile process_gov_logs.pid and
exits with error of running more than once.

If a logfile is specified it is rotated to a file logfile.rotated and the program waits for \'wait\'
seconds before processing. This allows the govlogger to close the file cleanly.

As some events may not be complete you can specify a state file to store remaining log events. This is
read at program start, and rewritten on exit allowing continual processing of log event without data loss.

   --canonical|-c Order fields alphanumerically
   --expires|-e   The number of seconds before a log event is output if no post-auth message has been
                  recieved. NOTE: Expiry is taken from the time on successive log events, not the time
                  now, as we may have a log backlog and we would not want to exire each entry.
                  Defaults to 30.
   --flush|-f     Push all data out at end, even if not complete log event, this is used mainly
                  during testing to ensure parsing split data file produces same output as single
                  datafile.
   --help|-h      Produces this help
   --logfile|-l   By default the program reads from stdin, if specified the file is renamed \'.rotated\'
                  and a then \'delay\' seconds are allowed to elapse before the file is opened for processing.
   --pretty|-p    Produces pretty JSON
   --reduce_duplicates     For repeated packets, such as those during a TLS key exchange only log a single
                           line with an array of dates for each packet.
   --reduce_last_date_only Only show the last date for entries with identical data, i.e. TLS negotiation
                           which would have 6 events logged. (Only works if reduce_duplicates enabled)
   --reduce_drop_eap_peap  Drop EAP-PEAP log events.
   --state|-s     Filename to restore and store state between invocations
   --wait|-w      Specify the number of seconds to wait when rotating an input file before processing
                  thus allowing all writers to have closed the file descriptor
';
}

# Create a pid file, and read previous, use LOCK_EX so only one
# process can own the file. DO NOT close the filehandle until
# all our work is done - else it's not an exlusive semaphore
sub create_pid_file {
    my ($pidfile) = @_;

    # Open the pidfile read write
    sysopen my $pid_filehandle, $pidfile, O_RDWR|O_CREAT
                || die qq/Cannot open pid file "$pidfile": $!\n/;

    my $maybe = <$pid_filehandle>;
    my ($pid) = $maybe =~ /^(\d+)/ if (defined $maybe);
    $pid ||= '?';

    # Try to get an exclusive lock on the pidfile
    flock($pid_filehandle, LOCK_EX | LOCK_NB)
        || die qq/pid "$pidfile" already locked (pid=$pid)\n/;

    print STDERR "Pid file from previous run still exists: (pid=$pid)\n"
        if $pid ne '?';

    # Seek back to start of file and truncate
    seek($pid_filehandle, 0, 0);
    truncate($pid_filehandle,0);

    print $pid_filehandle "$$\n";
    $pid_filehandle->flush;
    return $pid_filehandle;
}

sub unittests {
    #
    # Check lockfile
    #
    my $pidfile;
    eval {
        $pidfile = create_pid_file('/tmp/banana');
    };

    die("Failed to create pidfile /tmp/banana calling create_pid_file()\n") if !$pidfile;
    print "Pidfile /tmp/banana created\n";

    my $file = IO::File->new('/tmp/banana','r');
    die("Failed to open pidfile /tmp/banana: $!\n") if !$file;

    my $pid = $file->getline;
    chomp($pid);
    die("Pid file /tmp/banana did not contain a process id\n") if $pid !~ m/^\d+$/;
    print "Pidfile /tmp/banana contained pid $pid\n";

    die("Pid does not match programs $pid != $$\n") if $pid != $$;
    print "Pidfile /tmp/banana contained pid $pid, matching current process pid $$\n";

    my $second_lock;
    eval {
        $second_lock = create_pid_file('/tmp/banana');
    };

    die("Lock on /tmp/banana not exclusive, successfull second lock on calling create_pid_file()\n")
        if $second_lock;
    print "Failed to get second lock on /tmp/banana calling create_pid_file() - Success\n";

    $pidfile->close;
    eval {
        $second_lock = create_pid_file('/tmp/banana');
    };

    die("Failed to get lock on /tmp/banana after closing lock calling create_pid_file()\n")
        if !$second_lock;
    print "Successfully got second lock after closing previous calling create_pid_file()\n";
    $second_lock->close;
    unlink('/tmp/banana');

    #
    # Check linked list
    #
    my @items = (
        { name => 'entry0', Unixtime => 8 },
        { name => 'entry1', Unixtime => 10 },
        { name => 'entry2', Unixtime => 12 },
        { name => 'entry3', Unixtime => 14 },
        { name => 'entry4', Unixtime => 16 },
    );
        
    add_item_to_list($items[1]);
    add_item_to_list($items[3]);
    add_item_to_list($items[2]);
    add_item_to_list($items[4]);
    add_item_to_list($items[0]);

    check_items_in_right_order(@items);

    # remove item from middle
    remove_item_from_linked_list($items[2]);
    check_items_in_right_order($items[0], $items[1], $items[3], $items[4]);

    add_item_to_list($items[2]);
    check_items_in_right_order(@items);

    print "Item added back in ok\n";
    
    # remove item from start
    remove_item_from_linked_list($items[0]);
    check_items_in_right_order($items[1], $items[2], $items[3], $items[4]);

    print "Item remove ok from start\n";

    add_item_to_list($items[0]);
    check_items_in_right_order(@items);

    # remove item from start
    remove_item_from_linked_list($items[4]);
    check_items_in_right_order($items[0], $items[1], $items[2], $items[3]);

    print "Item remove ok from end\n";

    # Remove one before start...
    add_item_to_list($items[4]);
    remove_item_from_linked_list($items[1]);
    check_items_in_right_order($items[0], $items[2], $items[3], $items[4]);

    print "Item remove one before start ok\n";

    # Remove one before end...
    add_item_to_list($items[1]);
    remove_item_from_linked_list($items[3]);
    check_items_in_right_order($items[0], $items[1], $items[2], $items[4]);
}

sub check_items_in_right_order {
    my (@items) = @_;    
    my $start = $items_by_utime_start;
    my $index = 0;
    while ($start) {
        die("Item $index in linked list was not expected  ",$items[$index]{name}," but was $start->{name}\n")
            if $items[$index]{name} ne $start->{name};
        print "Item $index in linked list was as expected $start->{name}\n";
        $index++;
        $start = $start->{next};
    }

    die("Not all items found in list that were inserted\n") if $index != @items;
    print "Successfully found all items in list in right order\n";
}
 
